// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0AZY-E16Jyuwfr9f5pF6vwMWxOEXXcGA',
    appId: '1:58616196716:web:3d2f68b0ecd2fa4cc4b249',
    messagingSenderId: '58616196716',
    projectId: 'flash-ai-a25f9',
    authDomain: 'flash-ai-a25f9.firebaseapp.com',
    storageBucket: 'flash-ai-a25f9.firebasestorage.app',
    measurementId: 'G-QJQX1VZPPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL0vFyQnqBV0a1s_MXijdrrI-uAaKld6k',
    appId: '1:58616196716:android:940a3d985f490956c4b249',
    messagingSenderId: '58616196716',
    projectId: 'flash-ai-a25f9',
    storageBucket: 'flash-ai-a25f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgJj6IKdD5d2hI-aD723-8jrCmQCA0ok',
    appId: '1:58616196716:ios:3e4a56a07507a5d9c4b249',
    messagingSenderId: '58616196716',
    projectId: 'flash-ai-a25f9',
    storageBucket: 'flash-ai-a25f9.firebasestorage.app',
    iosClientId: '58616196716-opp566nvkstk1qjklhmbq68e3vc4r7b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempFlashAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfgJj6IKdD5d2hI-aD723-8jrCmQCA0ok',
    appId: '1:58616196716:ios:3e4a56a07507a5d9c4b249',
    messagingSenderId: '58616196716',
    projectId: 'flash-ai-a25f9',
    storageBucket: 'flash-ai-a25f9.firebasestorage.app',
    iosClientId: '58616196716-opp566nvkstk1qjklhmbq68e3vc4r7b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempFlashAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0AZY-E16Jyuwfr9f5pF6vwMWxOEXXcGA',
    appId: '1:58616196716:web:86fde1e73f83e973c4b249',
    messagingSenderId: '58616196716',
    projectId: 'flash-ai-a25f9',
    authDomain: 'flash-ai-a25f9.firebaseapp.com',
    storageBucket: 'flash-ai-a25f9.firebasestorage.app',
    measurementId: 'G-VPX9BB02J4',
  );
}
